functionsDirectory = "/Users/harryemes/Downloads/UniLingo_Website/netlify/functions"
functionsDirectoryOrigin = "config"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/Users/harryemes/Downloads/UniLingo_Website"
publishOrigin = "config"
commandOrigin = "config"
command = "npm install"
functions = "/Users/harryemes/Downloads/UniLingo_Website/netlify/functions"

[build.environment]
NODE_VERSION = "18"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/api/user-subscription/:userId"
to = "/.netlify/functions/user-subscription/:userId"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/create-checkout-session"
to = "/.netlify/functions/create-checkout-session"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/webhook"
to = "/.netlify/functions/webhook"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/cancel-subscription"
to = "/.netlify/functions/cancel-subscription"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/create-portal-session"
to = "/.netlify/functions/create-portal-session"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]