[build]
  command = "npm install"
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/create-checkout-session"
  to = "/.netlify/functions/create-checkout-session"
  status = 200

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook"
  status = 200

[[redirects]]
  from = "/cancel-subscription"
  to = "/.netlify/functions/cancel-subscription"
  status = 200

[[redirects]]
  from = "/reactivate-subscription"
  to = "/.netlify/functions/reactivate-subscription"
  status = 200

[[redirects]]
  from = "/create-portal-session"
  to = "/.netlify/functions/create-portal-session"
  status = 200

[[redirects]]
  from = "/subscription/:subscriptionId"
  to = "/.netlify/functions/subscription/:subscriptionId"
  status = 200

[[redirects]]
  from = "/account/:userId"
  to = "/.netlify/functions/account/:userId"
  status = 200

[[redirects]]
  from = "/account/:userId/settings"
  to = "/.netlify/functions/account/:userId/settings"
  status = 200

[[redirects]]
  from = "/api/user-subscription/:userId"
  to = "/.netlify/functions/user-subscription/:userId"
  status = 200

[[redirects]]
  from = "/api/update-stripe-customer"
  to = "/.netlify/functions/update-stripe-customer"
  status = 200

[[redirects]]
  from = "/api/config"
  to = "/.netlify/functions/config"
  status = 200

[[redirects]]
  from = "/api/test-supabase"
  to = "/.netlify/functions/test-supabase"
  status = 200

[[redirects]]
  from = "/health"
  to = "/.netlify/functions/health"
  status = 200

[build.environment]
  NODE_VERSION = "18"
