[build]
  command = "npm install"
  publish = "."

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/user-subscription/:userId"
  to = "/.netlify/functions/user-subscription/:userId"
  status = 200

[[redirects]]
  from = "/create-checkout-session"
  to = "/.netlify/functions/create-checkout-session"
  status = 200

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/webhook"
  status = 200

[[redirects]]
  from = "/cancel-subscription"
  to = "/.netlify/functions/cancel-subscription"
  status = 200

[[redirects]]
  from = "/create-portal-session"
  to = "/.netlify/functions/create-portal-session"
  status = 200

[build.environment]
  NODE_VERSION = "18"
